# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fa6a12256c39a3709bb5c6687dcccf06a579d8449579b2894687b6796be48e0f95eace8a1d54c34b0c8f7cb3812ed1d69b9684e13b96c03506915e0d83e576b

test:
  secret_key_base: 394b82af9aefd12d35e9f1c242d3047a9acea2db90d7c7a8c19b6a3838f8d92f3dc7f295502d0b1c3fcafd6bb1268ea6476ee9ae6035b7ed13a01cf778e4c073

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
